In [1]:
import numpy as np

In [17]:
a = np.array([1, 2, 3], dtype = "int32")
print(a)

[1 2 3]


In [18]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [19]:
# Get dimension

a.ndim
b.ndim

2

In [20]:
b.shape

(2, 3)

In [21]:
#Get type

a.dtype

dtype('int32')

In [22]:
a.itemsize

4

In [25]:
#Get total size no1

a.size * a.itemsize

12

In [26]:
#Get total size no2

a.nbytes

12

In [27]:
b.nbytes

48

In [29]:
a= np.array ([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [30]:
a.shape

(2, 7)

In [31]:
# 1 eilute yra nuline, 2 eilyte 1 ir t.t.
a[1, 5]

13

In [32]:
#get specific row: 1 skaicius eilute, antras skaicius stulpelis

a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [33]:
#get specific column

a[: , 2]

array([ 3, 10])

In [38]:
# Geting more fancy [startindex:endindex:stepsize]

a[0, 1:6:2]



array([2, 4, 6])

In [39]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [40]:
a[:, 2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [41]:
a[:, 2]=[1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [44]:
# 3 d example

b= np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [45]:
#get a specific element (work outside in). I puse pasirenkame su 0, tada antra eilute pasirenkame su 1, ir pasirenkame antra skaiciu su 1

b[0,1,1]

4

In [47]:
# jeigu nori antras eilutes is abieju elemetu isimti

b[: , 1, :]

array([[3, 4],
       [7, 8]])

In [49]:
# jeigu nori antrus stulpelius is abieju elemetu isimti

b[:, :, 1]

array([[2, 4],
       [6, 8]])

In [51]:
# replace

b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [52]:
# ALL 0s Matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [56]:
np.zeros((2, 3,))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [63]:
# ALL 1s Matrix

np.ones((4, 2, 2), dtype= "int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [62]:
# Any other number

np.full((2, 2 ), 99, dtype= "float32")

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [66]:
# any other number (full like) no1
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [67]:
# any other number (full like) no2
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [69]:
#Random decimal numbers (atsiminti kad nereikia dvigubu skliautu su random)
np.random.rand(4, 2, 3)

array([[[0.09231055, 0.41033094, 0.77289954],
        [0.21824023, 0.43414217, 0.64896931]],

       [[0.14840944, 0.67091322, 0.65111498],
        [0.48564146, 0.75890583, 0.36907979]],

       [[0.91057941, 0.49112741, 0.40494776],
        [0.51841653, 0.0366963 , 0.66472932]],

       [[0.3202708 , 0.99751054, 0.99792958],
        [0.48368934, 0.9136468 , 0.05360952]]])

In [70]:
#Random decimal numbers (atsiminti kad nereikia dvigubu skliautu su random)
np.random.random_sample(a.shape)

array([[0.8400005 , 0.13309767, 0.11664123, 0.8479785 , 0.85800073,
        0.92320462, 0.43412977],
       [0.95625415, 0.56329349, 0.22558806, 0.89583039, 0.003275  ,
        0.15570311, 0.06195235]])

In [76]:
# random integger numbers

np.random.randint(4, 8, size=(3,3))

array([[7, 4, 5],
       [6, 5, 5],
       [7, 6, 5]])

In [112]:
#The identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [83]:
#repeat an aray
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [89]:
#padaryti specifine lentele
output = np.ones((5,5))


z = np.zeros((3,3))
z[1, 1] = 9


output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [93]:
## be careful when copying arrays, nes pasikeicia abu pakeitus bent viena

a = np.array([1, 2, 3])
b = a
b[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]


In [94]:
# isspresti tai galima naudojant copy()

a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


In [95]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [96]:
a+2

array([3, 4, 5, 6])

In [97]:
a-2

array([-1,  0,  1,  2])

In [98]:
a*2

array([2, 4, 6, 8])

In [99]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [101]:
b = np.array([1, 0, 1, 0])
a+b

array([2, 2, 4, 4])

In [102]:
#kelimas laipsniu
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [103]:
#take the sin

np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [104]:
#take cosinus
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [105]:
####### Linear Algebra

In [109]:
a = np.ones((2, 3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [110]:
# find determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [113]:
### STatistics

In [115]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
np.min(stats, axis = 1)

array([1, 4])

In [121]:
np.max(stats, axis = 1)

array([3, 6])

In [125]:
np.sum(stats, axis=1)

array([ 6, 15])

In [126]:
np.sum(stats, axis = 0)

array([5, 7, 9])

In [129]:
before = np.array([[1,2,3, 4],[5,6,7,8]])
print(before)
print(before.shape)

after = before.reshape ((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [131]:
#verticlly stack vectors

v1 = np.array([1,2,3, 4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [136]:
#horizontal stack 

h1 = np.ones((2, 4))
h2 = np.zeros((2,2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [142]:
###Miscellaneous

filedata = np.genfromtxt ("C:/Users/Vartotojas/Desktop/Data.txt", delimiter = "," )
filedata = filedata.astype("int32")
filedata

array([[  1,   2,   4,   5,   6,   8,  55,  61],
       [  2,   9,   8,   7,  22, 333,  66,   7],
       [ 55,  44,  98,  13,  46,  78,  91,   0]])

In [143]:
## advancedindexing, Boolean, masking

In [145]:
filedata>=50

array([[False, False, False, False, False, False,  True,  True],
       [False, False, False, False, False,  True,  True, False],
       [ True, False,  True, False, False,  True,  True, False]])

In [146]:
filedata[filedata>=50]

array([ 55,  61, 333,  66,  55,  98,  78,  91])

In [147]:
### can index with alist

In [148]:
a= np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [149]:
# axis 0 yra stulpeliai, axis 1 yra eilutes. Bent vienas stulpelyje eatitinka any finkcija
np.any(filedata>=50, axis = 0)

array([ True, False,  True, False, False,  True,  True,  True])

In [150]:
#visi stulpelyje atitinka
np.all(filedata>=50, axis = 0)

array([False, False, False, False, False, False,  True, False])

In [152]:
#kombinuota salyga
((filedata>=50) & (filedata<100))

array([[False, False, False, False, False, False,  True,  True],
       [False, False, False, False, False, False,  True, False],
       [ True, False,  True, False, False,  True,  True, False]])

In [153]:
#kombinuota salyga su salyga not ~
(~(filedata>=50) & (filedata<100))

array([[ True,  True,  True,  True,  True,  True, False, False],
       [ True,  True,  True,  True,  True, False, False,  True],
       [False,  True, False,  True,  True, False, False,  True]])